package gui;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;

public class FormLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblCR = new javax.swing.JLabel();
        lblnombreE1 = new javax.swing.JLabel();
        lblSlogan1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogin = new javax.swing.JLabel();
        lblCrear = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblUsuario1 = new javax.swing.JLabel();
        lblnoC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 56, 78));
        jPanel1.setMinimumSize(new java.awt.Dimension(1126, 657));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/apolo - Editado (1).png"))); // NOI18N
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        lblCR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCR.setForeground(new java.awt.Color(0, 56, 78));
        lblCR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCR.setText("copyright ©️ Centro Apolo All rights reserved");
        jPanel3.add(lblCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 850, 40));

        lblnombreE1.setFont(new java.awt.Font("Arial Black", 1, 42)); // NOI18N
        lblnombreE1.setForeground(new java.awt.Color(0, 56, 78));
        lblnombreE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombreE1.setText("CENTRO INFORMÁTICO");
        jPanel3.add(lblnombreE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 850, -1));

        lblSlogan1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSlogan1.setForeground(new java.awt.Color(0, 56, 78));
        lblSlogan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan1.setText("Tu aliado en innovación tecnológica");
        jPanel3.add(lblSlogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 850, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 1050));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 56, 78));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, 10));

        lblLogin.setBackground(new java.awt.Color(48, 54, 79));
        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 56, 78));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("INICIO DE SESIÓN");
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 490, -1));

        lblCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCrear.setForeground(new java.awt.Color(255, 0, 0));
        lblCrear.setText("Crear una Aquí");
        lblCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearMouseClicked(evt);
            }
        });
        jPanel2.add(lblCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        lblContra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblContra.setForeground(new java.awt.Color(0, 56, 78));
        lblContra.setText("Contraseña");
        jPanel2.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 380, 40));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 380, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/inicioSesion (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 250, 200));

        btnIniciar.setBackground(new java.awt.Color(0, 56, 78));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);
        jPanel2.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 140, 40));

        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(0, 56, 78));
        lblUsuario1.setText("Usuario");
        jPanel2.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        lblnoC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnoC.setForeground(new java.awt.Color(0, 56, 78));
        lblnoC.setText("No tengo cuenta");
        jPanel2.add(lblnoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, 560));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        String user = txtUsuario.getText();
        // Si usaste un JPasswordField, se obtiene así:
        String pass = new String(txtPass.getPassword()); 
        // Si usaste un JTextField normal, sería simplemente: txtContrasena.getText();

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tu usuario y contraseña.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UsuarioDAO dao = new UsuarioDAO();
        
        // Llamamos al método que creamos en el DAO
        if (dao.validarLogin(user, pass)) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido, " + user + "!");
            
            // Instanciamos y abrimos el Menú Principal
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            
            // Cerramos esta ventana de Login
            this.dispose(); 
            
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas o usuario dado de baja.", "Error de Login", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearMouseClicked
        // TODO add your handling code here:
        FormCrearCuenta crearCuenta = new FormCrearCuenta();
        crearCuenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCR;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSlogan1;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblnoC;
    private javax.swing.JLabel lblnombreE1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
